<a href="https://colab.research.google.com/github/thiviyan98/ThiviyanNanthakumarCE888/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np

# random cells =99 as the jokes are not rated
df= pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv', header= None)

print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


##Helper Function

In [43]:
arr = df.values
print(arr.shape)

(24983, 101)


In [44]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835357 (1835357,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [46]:
new_arr, idx = replace(arr, 0.1)

print(new_arr)
print(idx) #validation set

print(arr[idx[0][0], idx[1][0]])

print(new_arr[idx[0][0], idx[1][0]])

[[ 74.    -7.82   8.79 ...  99.    99.    99.  ]
 [100.     4.08  99.   ...   0.34  -4.32   1.07]
 [ 49.    99.    99.   ...  99.    99.    99.  ]
 ...
 [ 39.    99.    99.   ...  99.    99.    99.  ]
 [ 37.    99.    99.   ...  99.    99.    99.  ]
 [ 72.     2.43   2.67 ...  99.    99.    99.  ]]
(array([10343, 18940, 17600, ..., 22790,  1636, 13743]), array([52, 22, 32, ..., 51, 11, 60]))
7.28
99.0


##Latent Factor Modelling to infer Hidden Ratings of the users

In [0]:
n_latent_factors=5

user_ratings=arr

# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [63]:
latent_item_features

array([[0.62061279, 0.75298356, 0.70326791, 0.49374238, 0.99761423],
       [0.41230202, 0.20446941, 0.72844863, 0.35014588, 0.68777982],
       [0.45720823, 0.8432533 , 0.44977146, 0.31310766, 0.93023012],
       [0.00972908, 0.5996606 , 0.30465358, 0.6853633 , 0.56748746],
       [0.04413899, 0.35557657, 0.17385063, 0.87980118, 0.02798794],
       [0.24045911, 0.20764127, 0.41695158, 0.00735108, 0.62799764],
       [0.0326643 , 0.43206212, 0.6951509 , 0.90767309, 0.55748547],
       [0.48655825, 0.25732072, 0.80927818, 0.6709815 , 0.92202022],
       [0.62702023, 0.78971142, 0.23195712, 0.24345471, 0.87063273],
       [0.21143188, 0.09579828, 0.93418062, 0.1376297 , 0.70431716],
       [0.55348785, 0.61252862, 0.34900765, 0.31663752, 0.06434165],
       [0.05925061, 0.20116877, 0.4201659 , 0.88909519, 0.77189914],
       [0.87600722, 0.66351626, 0.97415118, 0.23122218, 0.43371947],
       [0.3364737 , 0.86922734, 0.87578086, 0.11963541, 0.51146348],
       [0.14118778, 0.63056745, 0.

In [64]:
latent_user_preferences

array([[0.86280176, 0.32338368, 0.8529395 , 0.0868466 , 0.3869725 ],
       [0.64578692, 0.48826018, 0.15565562, 0.1462454 , 0.34946404],
       [0.45072874, 0.43293574, 0.48888282, 0.86745475, 0.55191893],
       ...,
       [0.27590497, 0.62565027, 0.82901585, 0.74950984, 0.65526915],
       [0.85783496, 0.33111735, 0.47422199, 0.72001882, 0.47837717],
       [0.11002355, 0.51909169, 0.88641066, 0.91246758, 0.70186002]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [66]:
sgd()  # Note how the MSE decreases with the number of iterations

44.45123139813688
24.52230507100866
20.33469966275896
18.008656782244874
17.764682490487523


In [67]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[76.40960927, -3.92355721, -3.34703422, ..., -3.11132564,
        -5.21691397, -2.72526639],
       [95.59765272,  3.78821993,  2.59947252, ...,  2.28691532,
         2.27763338,  2.73349357],
       [49.18655772,  6.8244959 ,  6.88627138, ...,  7.56697259,
         7.40059282,  8.20857642],
       ...,
       [39.38899387,  0.74412662, -0.4437974 , ..., -0.86151815,
        -0.40678031, -0.8967705 ],
       [37.97507621, -0.84349164, -0.95564455, ..., -0.36959259,
        -1.01961784, -0.20849695],
       [73.77656052,  4.00683374,  2.99764661, ...,  2.97270589,
         2.99526457,  3.33677266]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [69]:
comparison_data

0    ...                          100
0        (74.0, 76.40960927031135)  ...   (99.0, -2.725266391341411)
1       (100.0, 95.59765271841682)  ...    (1.07, 2.733493572403851)
2        (49.0, 49.18655771982009)  ...    (99.0, 8.208576423504965)
3        (48.0, 48.30456296326805)  ...    (99.0, 3.217132509016169)
4        (91.0, 91.42255571016888)  ...     (1.6, 4.389246108682532)
...                            ...  ...                          ...
24978  (100.0, 101.45821273323706)  ...   (7.43, 3.4728830684040988)
24979    (91.0, 87.31759934160306)  ...  (8.45, 0.09184476574448311)
24980    (39.0, 39.38899387476653)  ...   (99.0, -0.896770503629943)
24981   (37.0, 37.975076211013246)  ...  (99.0, -0.2084969481114607)
24982    (72.0, 73.77656052153692)  ...    (99.0, 3.336772664096239)

[24983 rows x 101 columns]

##valid set

In [0]:
n_latent_factors=5

user_ratings=new_arr

# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [72]:
sgd()

45.81714597232098
24.495600223368964
21.812859323939602
18.09686422977399
17.786854421167423


In [73]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[76.94005212, -2.94561255, -3.44255855, ..., -2.91496868,
        -4.77158038, -3.17413902],
       [94.83871681,  2.61379355,  2.39936368, ...,  2.52428582,
         1.10052024,  3.23352708],
       [48.77405572,  5.9135078 ,  7.17657355, ...,  7.86793164,
         6.06280058,  8.49344846],
       ...,
       [39.72395664, -0.59705699, -1.18268985, ..., -1.28104652,
        -1.55618059, -1.01613034],
       [37.57139076, -0.48515849, -0.29867055, ...,  0.45881584,
        -1.0676126 ,  0.51710274],
       [72.67125347,  2.6484836 ,  2.62517564, ...,  3.56140119,
         2.15843647,  4.06058654]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [75]:
comparison_data

0    ...                          100
0         (74.0, 76.9400521230569)  ...  (99.0, -3.1741390213541916)
1        (100.0, 94.8387168136915)  ...    (1.07, 3.233527079961607)
2        (49.0, 48.77405571627237)  ...     (99.0, 8.49344846349271)
3       (48.0, 48.313377575862056)  ...    (99.0, 3.236391633741332)
4        (91.0, 91.29303961626003)  ...      (1.6, 4.31227728220092)
...                            ...  ...                          ...
24978  (100.0, 100.82263264041106)  ...    (7.43, 4.069169410175758)
24979    (91.0, 86.00178252279392)  ...   (8.45, 1.6218610762895609)
24980    (39.0, 39.72395663982374)  ...   (99.0, -1.016130341887355)
24981   (37.0, 37.571390756791715)  ...     (99.0, 0.51710274163457)
24982    (72.0, 72.67125347230461)  ...    (99.0, 4.060586536323983)

[24983 rows x 101 columns]

In [0]:
## the performance of the algorithm on the validation dataset was worse than on the orignal dataset. 


